#! /bin/sh
#
# Copyright (c) 2017 Rouven Spreckels <n3vu0r@qu1x.org>
#
# Usage of the works is permitted provided that
# this instrument is retained with the works, so that
# any entity that uses the works is notified of this instrument.
#
# DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.

over=${LOOKATME_OVER:-"http"}
from=${LOOKATME_FROM:-"ipvx.qu1x.net"}

look() {
	curl --silent --show-error --ipv$1 "$over://$from"
}

help="\
Look at me and tell me my IPv4 and IPv6 address

lookatme [OPTION]
  ...via IPv4 and IPv6 in parallel (output unordered)

OPTIONs:
  -4             Via IPv4 only
  -6             Via IPv6 only
  -h, --help     Print help
  -v, --version  Print version

Environment variables:
  LOOKATME_OVER  $over
  LOOKATME_FROM  $from"
info="\
v1.0.0 <https://qu1x.org/lookatme>"
hint="\
Invalid usage, see --help"

test $# -le 1 || hint
case $1 in
	'')
		look 4 & pid4=$!
		look 6 & pid6=$!
		wait $pid4; ret4=$?
		wait $pid6; ret6=$?
		exit $(($ret4+$ret6)) ;;
	-4)
		look 4 ;;
	-6)
		look 6 ;;
	-h|--help)
		echo "$help" ;;
	-v|--version)
		echo "$info" ;;
	*)
		echo "$hint" 1>&2; exit 2 ;;
esac
